JobApp/JobApp/Controllers/AdminController.cs
using JobApp.Data;
using JobApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JobApp.Areas.Admin.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly ApplicationDBContext _context;

        public AdminController(ApplicationDBContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            return _context.JobApplications != null ?
                        View(await _context.JobApplications.ToListAsync()) :
                        Problem("Entity set 'JobApplicationDBContext.JobApplications'  is null.");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.JobApplications == null)
            {
                return NotFound();
            }

            var jobApplicationData = await _context.JobApplications
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jobApplicationData == null)
            {
                return NotFound();
            }

            return View(jobApplicationData);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.JobApplications == null)
            {
                return NotFound();
            }

            var jobApplicationData = await _context.JobApplications.FindAsync(id);
            if (jobApplicationData == null)
            {
                return NotFound();
            }
            return View(jobApplicationData);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, JobApplicationData jobApplicationData)
        {
            if (id != jobApplicationData.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    JobApplicationDTO jobApplication = new JobApplicationDTO
                    {
                        Id = jobApplicationData.Id,
                        Name = jobApplicationData.Name,
                        Email = jobApplicationData.Email,
                        Gender = jobApplicationData.Gender,
                        Contact = jobApplicationData.Contact,
                        Address = jobApplicationData.Address,
                        PreferredLocation = jobApplicationData.PreferredLocation,
                        ExpectedCTC = jobApplicationData.ExpectedCTC,
                        CurrentCTC = jobApplicationData.CurrentCTC,
                        NoticePeriod = jobApplicationData.NoticePeriod,
                        Ccharpexperience = jobApplicationData.Ccharpexperience,
                        Mssqlexperience = jobApplicationData.Mssqlexperience,
                        dotnetexperience = jobApplicationData.dotnetexperience,
                        devopsexperience = jobApplicationData.devopsexperience,
                    };
                    _context.Update(jobApplication);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobApplicationDataExists(jobApplicationData.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(jobApplicationData);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.JobApplications == null)
            {
                return NotFound();
            }

            var jobApplicationData = await _context.JobApplications
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jobApplicationData == null)
            {
                return NotFound();
            }

            return View(jobApplicationData);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.JobApplications == null)
            {
                return Problem("Entity set 'JobApplicationDBContext.JobApplications'  is null.");
            }
            var jobApplicationData = await _context.JobApplications.FindAsync(id);
            if (jobApplicationData != null)
            {
                _context.JobApplications.Remove(jobApplicationData);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool JobApplicationDataExists(int id)
        {
            return (_context.JobApplications?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

JobApp/JobApp/Controllers/JobApplicationController.cs
using JobApp.Data;
using JobApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace JobApp.Controllers
{
    
    public class JobApplicationController : Controller
    {

        private readonly ApplicationDBContext _context;

        public JobApplicationController(ApplicationDBContext context)
        {
            _context = context;
        }
      
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(JobApplicationData jobApplicationData)
        {
            if (ModelState.IsValid)
            {
                JobApplicationDTO jobApplication = new JobApplicationDTO
                {
                    Name = jobApplicationData.Name,
                    Email = jobApplicationData.Email,
                    Gender = jobApplicationData.Gender,
                    Contact = jobApplicationData.Contact,
                    Address = jobApplicationData.Address,
                    PreferredLocation = jobApplicationData.PreferredLocation,
                    ExpectedCTC = jobApplicationData.ExpectedCTC,
                    CurrentCTC = jobApplicationData.CurrentCTC,
                    NoticePeriod = jobApplicationData.NoticePeriod,
                    Ccharpexperience = jobApplicationData.Ccharpexperience,
                    Mssqlexperience = jobApplicationData.Mssqlexperience,
                    dotnetexperience = jobApplicationData.dotnetexperience,
                    devopsexperience = jobApplicationData.devopsexperience,
                };
                _context.JobApplications.Add(jobApplication);
                await _context.SaveChangesAsync();

                foreach (var edu in jobApplicationData.Educations)
                {
                    edu.JobApplicationId = jobApplication.Id;
                    _context.Educations.Add(edu);
                    await _context.SaveChangesAsync();
                }
                foreach (var work in jobApplicationData.WorkExperiences)
                {
                    work.JobApplicationId = jobApplication.Id;
                    _context.WorkExperiences.Add(work);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index));
            }
            return View(jobApplicationData);
        }

    }
}

JobApp/JobApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JobApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JobApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="JobApplication" asp-action="Create">JobApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (SignInManager.IsSignedIn(User))
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>

                            <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <button class="nav-link text-dark" type="submit">Logout</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                }
            </div>
        </nav>
        @*<partial name="_LoginPartial"/>*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - JobApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>